### ISSUE TITLE
Allow easier Pocket list sync

### ISSUE THREAD

**Issue by oldjove** [nybbles/obsidian-pocket#38]
Another potential feature: Have the option to automatically sync the Pocket list when opening it. Or failing that, add a hotkey to sync the list. As far as I can tell, at the moment the only way to sync the list is to navigate to the plugin options and do it there. This is a little awkward IMO.

Thanks!

**Comment by nybbles** [comment]
Agreed. I just left it at the simplest possible thing, but I definitely will look into adding this.

**Comment by nybbles** [comment]
I'm going to go with the command route, where there will be a command for syncing the Pocket list. You can then bind a hotkey to it.

**Comment by oldjove** [comment]
Sounds like a good solution. Thanks.
