### ISSUE TITLE
Display tags in Pocket item list

### ISSUE THREAD

**Issue by rezgi** [nybbles/obsidian-pocket#43]
Hello. First thank you very much for making this plugin, it really helps me bring everything in my Obsidian knowledge system.

I was surprised to find that tags aren't imported so I'd like to request for this feature. I've checked Pocket's API and there's a lot that can be done for images, videos and such.

And sorry, I want to make this a feature request but don't know how to add the label :)

Thank you very much !

**Comment by nybbles** [comment]
oops i just realized that i still need to make it possible for tags to be added to a Pocket item note via template. I'll file an issue to track that and get to it soon.

**Comment by rezgi** [comment]
Thank you very much for being so reactive !!
