### ISSUE TITLE
Pocket connected, sync works, MD file is created, but contains nothing

### ISSUE THREAD

**Issue by pivic** [nybbles/obsidian-pocket#45]
Hi there!

I've installed this lovely plugin, connected it to my Pocket account, synced my list, and it is displayed when I select the 'Open Pocket' command in Obsidian.

When I select one of the links, an MD file is created for that specific article, but here's my problem: the file contains nothing. The MD file is 0 bytes large.

Am I doing something wrong here? Sorry, I'm a noob.

Thank you very much for this plugin!

**Comment by pivic** [comment]
Thank you so much, @nybbles! Your very kind and instructive words helped me completely. Cheers!

**Comment by nybbles** [comment]
My pleasure!
