### ISSUE TITLE
Feature request: to import everything from a Pocket article

### ISSUE THREAD

**Issue by pivic** [nybbles/obsidian-pocket#48]
Currently, the plugin imports an excerpt of a Pocket article.

I would actually like it if it were possible to import a Pocket article in its entirety, at least the text (i.e. no images). This would be wonderful.

**Comment by nybbles** [comment]
closing this, since it requires obsidian-pocket to be whitelisted and that's not a priority at the moment. Noted that full text import of the article would be valuable.
