### ISSUE TITLE
Handle multi-word tags

### ISSUE THREAD

**Issue by nybbles** [nybbles/obsidian-pocket#50]
Tags in Pocket can have whitespace in them, whereas tags in Obsidian cannot. "#energy models" is valid on Pocket, but not in Obsidian.

The behavior has to make sense in both the Pocket item list and in the Pocket item note created from a template.

Allow the user to pick how they want to handle tags, i.e.:
1. Transform to snake_case (default?).
2. Transform to camelCase.
3. Do nothing (this will break multi-word tags).

**Comment by rezgi** [comment]
They're all good options, maybe leave it as an option in the plugin settings ? snake_case by default is the clearest imo.
