### ISSUE TITLE
Provide the option to open the item directly in Pocket or the original

### ISSUE THREAD

**Issue by ahue** [nybbles/obsidian-pocket#70]
Current behavior: 
Alt + Click opens the original

Proposed behavior
- Two further links are added (possibly righ-aligned): "Open in Pocket", "Open Original"
- One link opens the note in pocket
- The other link opens the original (possibly replaces Alt + Click after a grace period)

Example item
![image](https://user-images.githubusercontent.com/198609/148677203-e574d5b4-bbed-42b4-a8ba-86b554ee074a.png)

**Comment by KierenB** [comment]
Even the option to embed `{{pocket-url}}` into a template would be sweet.

**Comment by nybbles** [comment]
yea this makes sense.. not sure when I'll get to it, so patches are welcome. It's on my radar though; just letting you all know.

**Comment by nybbles** [comment]
resolved in #89

**Comment by nybbles** [comment]
Update to 0.7.1 to get this functionality. Thanks again @ashlyn.
