### ISSUE TITLE
{{tags}} placeholder gets tags with #-prefixed --> messes-up meta data

### ISSUE THREAD

**Issue by ahue** [nybbles/obsidian-pocket#71]
## Current behavior
When using the {{tags}} placeholder in the meta section, tags get put in the #-sign prefixed; This causes obsidian to render the meta data invalid an e.g. the graph view not to catch on to the tag.
```
---
title: ...
url: ...
tags: [{{tags}}, pocket-note]
excerpt: >
---
```
results in
```
---
title: ...
url: ...
tags: [#tag1, #tag2, pocket-note]
excerpt: >
---
```
leading to
![image](https://user-images.githubusercontent.com/198609/148677989-76db48de-e160-41d5-8cdd-27d20e3905ca.png)

and
![image](https://user-images.githubusercontent.com/198609/148678010-078b514c-404d-4221-8243-11ec9c703f19.png)

Nevertheless, I understand that {{tags}} used in the notes body need the #-sign to be captured by obsidian as such.

### Option 1
Change the {{tags}} behavior to return the comma-separated list without #-sign, add a {{tags#}} placeholder to put in the tags with leading #-sign.

Caveats: this will break templates, using the {{tags}} placeholder in the note body.

### Option 2
Add a {{tags-no-hash}} (or similarly named) placeholder that returns the comma-separated list without #-sign

**Comment by nybbles** [comment]
thanks for raising this. I didn't realize that tags behave differently between front matter and body. Thanks for the clear description and proposed behavior. I think that I'll go with Option 2, as it would be the least disruptive.

**Comment by nybbles** [comment]
You can get this functionality now by updating the plugin via the Obsidian app.
