### ISSUE TITLE
Plugin isn't creating a file

### ISSUE THREAD

**Issue by webhead404** [nybbles/obsidian-pocket#72]
Hello and thanks for this great plugin! I am super excited to use it. After installation I noticed that a note with the Pocket items isn't being created. I have tested with a few different vaults in different locations to see if it was a permission problem but it doesn't appear so. The plugin states that it fetches my items but no `.md` file is created in the folder I specified. 

If this is related to the community plugin install not working correctly is it possible to get some instructions on installing manually from source? 

Thanks!

**Comment by webhead404** [comment]
Okay I noticed #45 after I made this issue, I created a template file as well and I didn't see a change. 

I specified the folder like this `ReadingList/` to direct the file to that folder in my vault. and created a template in this form`Templates/Pocket` with the example template given here: https://github.com/nybbles/obsidian-pocket#using-templates-for-pocket-notes

Am I missing something obvious? Thank you!

**Comment by webhead404** [comment]
Okay I found the Open Pocket list and now I understand how this works better. It would be awesome to export this directly to it's own note but I now understand how the templates are used. Very awesome and useful. Thank you!

**Comment by nybbles** [comment]
Hey glad you're finding the plug-in useful and managed to sort out your issue!

Can you tell me what happened here and what you're asking for? Was it that you weren't aware of the fact that you have to open the Pocket list and click the Pocket list item to create a note for a Pocket item, and so you were wondering where your Pocket item notes were?

And in your last comment, are you asking for the default behavior to be that Pocket item notes are automatically created?

**Comment by webhead404** [comment]
Yes my original belief was that the plugin would create one note with my Pocket list. I wasn't aware that I needed to run the command. Then once I discovered that I needed a template it made sense. 

Yes it would be nice to have the option to just sync them all to one note but I realize some of the challenges with this. For instance I identified an issue with error handling with URL's that didn't have a title parsed correctly in Pocket. (Can't create notes with `https://` for obvious reasons)

If the command structure needs to be set a feature request, that would be beneficial is to be able to select notes by holding CTL or SHIFT in the Pocket window rather than having to run the Pocket command all the time everytime you want to open one of the notes. Hopefully that makes some sense?

**Comment by nybbles** [comment]
Hey sorry for the delayed response. I'm kinda carving time out where I can 😅

Rather than having to click+multi-select to create notes for multiple Pocket items at a time, would your needs be served if Pocket item notes were created automatically whenever Pocket items are synced?

**Comment by webhead404** [comment]
No issue at all, I understand! Yes I would prefer that personally! Even if it was one note with all the Pocket items in it that would work too!
