### ISSUE TITLE
Is it possible to load the image as well?

### ISSUE THREAD

**Issue by kenjibailly** [nybbles/obsidian-pocket#76]
In Pocket the list shows images of the site saved.
Is it possible to add the images to the note template (Templater)?

**Comment by nybbles** [comment]
It looks like it's available in the API and saved in `obsidian-pocket`'s database, so yea it's possible. It would involve fetching the image, saving it locally to Obsidian's vault and then embedding it in the Obsidian note. Or did you mean rendering it in the Pocket item list?

I don't think that the `obsidian-pocket` plugin should necessarily be downloading and saving/caching images locally though. That seems like it would not be expected by the Obsidian user, even if those images are rendered in Pocket itself.

I think that if you are really interested in this feature, you'd have to make a stronger case for it and it's high-effort/low-priority enough that I would not build it myself, but would rather accept a patch (assuming the case has been made for it).

**Comment by nybbles** [comment]
Actually I think this should be possible via template, and image url.

**Comment by nybbles** [comment]
@kenjibailly got this working for the single image (`image` in the API object). Can you provide your perspective on how this should work?

Current behavior I have implemented for the `{{image}}` template tag:
1. for a Pocket item that does have an image, `{{image}}` will be substituted with `![image](https://image-url/something.png)`
2. for a Pocket item that does not have an image, `{{image}}` will be substituted with the empty string "", essentially a no-op.

I could expose the image source URL and then allow the user to create the `![something](https://someurl/)`, but that would not work nicely when the Pocket item lacks an image.

LMK what you think.

**Comment by nybbles** [comment]
Attached the PR in case you're interested in the implementation.

**Comment by kenjibailly** [comment]
> @kenjibailly got this working for the single image (`image` in the API object). Can you provide your perspective on how this should work?
> 
> Current behavior I have implemented for the `{{image}}` template tag:
> 
> 1. for a Pocket item that does have an image, `{{image}}` will be substituted with `![image](https://image-url/something.png)`
> 2. for a Pocket item that does not have an image, `{{image}}` will be substituted with the empty string "", essentially a no-op.
> 
> I could expose the image source URL and then allow the user to create the `![something](https://someurl/)`, but that would not work nicely when the Pocket item lacks an image.
> 
> LMK what you think.

So how I would see this work is have the objects attached to a permanent note instead of opening a note like page that isn't saved anywhere.
If it's saved to an actual note then I could use dataview to show them wherever I want

**Comment by nybbles** [comment]
Implemented in #86, which just merged. Not released yet.

**Comment by nybbles** [comment]
This is released and available now in 0.8.0. LMK if you have any issues and if this meets your needs.
