### ISSUE TITLE
Synced List Does not Persist after Closing

### ISSUE THREAD

**Issue by ticmain** [nybbles/obsidian-pocket#80]
Sync'd items get pulled into Pocket list as expected.

However, if you close and reopen the list, the page displays "No items synced!"

Re-running the Sync command and the dialogs show no new items added, but the list re-displays.

**Comment by nybbles** [comment]
when you ran the sync command, did you see an Obsidian in-app notice that said something like "Fetched n updates from Pocket"? What was the value of "n"?

**Comment by nybbles** [comment]
@ticmain are you still experiencing this issue?

**Comment by ticmain** [comment]
@nybbles no. the issue has been resolved. Thanks!
